version:    "3"
services:
    prometheus:
# Prometheus server broadcasting on 9090 
        image:  "prom/prometheus"
        volumes:    
            - /Users/sbhat/PrometheusTestStuff/Docker/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - "9090:9090"
    pushgateway_2:
# pushgateway service broadcasting on 9091
        image:  "prom/pushgateway"
        ports:
            - "9091:9091"
        


         
